In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data_movies= pd.read_csv('PI_MLOps/movies_dataset.csv')
data_credits= pd.read_csv('PI_MLOps/credits.csv')

C:\Users\Jocelyn\AppData\Local\Temp\ipykernel_18376\977404445.py:5: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  data_movies= pd.read_csv('PI_MLOps/movies_dataset.csv')

En esta parte hacemos todos los puntos que se piden menos el desanidado de las columnas

In [2]:
#Eliminamos las columnas que no se van a utilizar: video,imdb_id,adult,original_title,poster_path y homepage.
data_movies= data_movies.drop(['video','imdb_id','adult','original_title','poster_path','homepage'], axis=1)
#Los valores nulos del campo release date deben eliminarse.
data_movies= data_movies.dropna(subset=['release_date'])
#Los valores nulos de los campos revenue, budget deben ser rellenados por el número 0.
values = {"revenue": 0, "budget": 0}
data_movies=data_movies.fillna(value=values)
#Crear la columna con el retorno de inversión, llamada return con los campos revenue y budget, dividiendo 
# estas dos últimas revenue / budget, cuando no hay datos disponibles para calcularlo, deberá tomar el valor 0.
data_movies['revenue']=pd.to_numeric(data_movies['revenue'], errors ='coerce')
data_movies['budget']=pd.to_numeric(data_movies['budget'], errors ='coerce')
data_movies['return']=data_movies['revenue'].div(data_movies['budget']).replace(np.inf, 0).replace(np.NaN,0)
#De haber fechas, deberán tener el formato AAAA-mm-dd, además deberán crear la columna release_year donde extraerán el año de la fecha de estreno.
len('1995-10-30')
from datetime import datetime, date

# Definimos la función para convertir un string de fecha a un objeto date
def convert_to_date(date_string):
    if len(date_string)!=10:
        date_string= np.nan
    else:
        return datetime.strptime(date_string, '%Y-%m-%d')


#Aplicamos la función a la columna release_date
data_movies['release_date']= data_movies['release_date'].apply(convert_to_date)

data_movies['release_date'].isnull().sum()
data_movies= data_movies.dropna(subset=['release_date'])
#Creamos la columna con sólo el año 
data_movies['release_year']=data_movies['release_date'].dt.year

En esta parte se hace el desanidado de las columnas

In [3]:
#convertirmos la columna id de objeto a entero para poder hacer el merge
data_movies['id'] = data_movies['id'].astype(int)
#Juntamos los dataframes:créditos y las películas
data_movies_credits=data_movies.merge(data_credits,on='id')


#Vericamos que no haya valores repetidos de 2 formas:
data_movies_credits['id'].value_counts()
data_movies_credits.duplicated().sum()
#Y los eliminamos
data_movies_credits.drop_duplicates(inplace=True)

In [40]:
data_movies_credits

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,...,spoken_languages,status,tagline,title,vote_average,vote_count,return,release_year,cast,crew
0,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,7.7,5415.0,12.451801,1995,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,NaN,65000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,en,When siblings Judy and Peter discover an encha...,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0,4.043035,1995,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0.0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,en,A family wedding reignites the ancient feud be...,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0,0.000000,1995,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,NaN,16000000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0,5.090760,1995,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,"{'id': 96871, 'name': 'Father of the Bride Col...",0.0,"[{'id': 35, 'name': 'Comedy'}]",11862,en,Just when George Banks has recovered from his ...,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0,0.000000,1995,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45446,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",30840,en,"Yet another version of the classic epic, with ...",5.683753,"[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1991-05-13,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Robin Hood,5.7,26.0,0.000000,1991,"[{'cast_id': 1, 'character': 'Sir Robert Hode'...","[{'credit_id': '52fe44439251416c9100a899', 'de..."
45447,NaN,0.0,"[{'id': 18, 'name': 'Drama'}]",111109,tl,An artist struggles to finish his work while a...,0.178241,"[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,...,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,9.0,3.0,0.000000,2011,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de..."
45448,NaN,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",67758,en,"When one of her hits goes wrong, a professiona...",0.903007,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,3.8,6.0,0.000000,2003,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de..."
45449,NaN,0.0,[],227506,en,"In a small town live two brothers, one a minis...",0.003503,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,...,[],Released,NaN,Satan Triumphant,0.0,0.0,0.000000,1917,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de..."
45450,NaN,0.0,[],461257,en,50 years after decriminalisation of homosexual...,0.163015,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,0.0,0.0,0.000000,2017,[],"[{'credit_id': '593e676c92514105b702e68e', 'de..."

In [4]:
#Verificamos los tipos de objeto que tienen las columnas anidadas
print('belongs_to_collection: ',type(data_movies_credits.iloc[0].belongs_to_collection))
print(data_movies_credits.iloc[0].belongs_to_collection)
print('genres: ',type(data_movies_credits.iloc[0].genres))
print(data_movies_credits.iloc[0].genres)
print('production_companies: ',type(data_movies_credits.iloc[0].production_companies))
print(data_movies_credits.iloc[0].production_companies)
print('production_countries: ',type(data_movies_credits.iloc[0].production_countries))
print(data_movies_credits.iloc[0].production_countries)
print('spoken_languages: ',type(data_movies_credits.iloc[0].spoken_languages))
print(data_movies_credits.iloc[0].spoken_languages)
print('cast: ',type(data_movies_credits.iloc[0].cast))
print(data_movies_credits.iloc[0].cast)
print('crew: ',type(data_movies_credits.iloc[0].crew))
print(data_movies_credits.iloc[0].crew)

belongs_to_collection:  <class 'str'>
{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}
genres:  <class 'str'>
[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]
production_companies:  <class 'str'>
[{'name': 'Pixar Animation Studios', 'id': 3}]
production_countries:  <class 'str'>
[{'iso_3166_1': 'US', 'name': 'United States of America'}]
spoken_languages:  <class 'str'>
[{'iso_639_1': 'en', 'name': 'English'}]
cast:  <class 'str'>
[{'cast_id': 14, 'character': 'Woody (voice)', 'credit_id': '52fe4284c3a36847f8024f95', 'gender': 2, 'id': 31, 'name': 'Tom Hanks', 'order': 0, 'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'}, {'cast_id': 15, 'character': 'Buzz Lightyear (voice)', 'credit_id': '52fe4284c3a36847f8024f99', 'gender': 2, 'id': 12898, 'name': 'Tim Allen', 'order': 1, 'profile_path': '/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg'}, {'cast_id': 16, 'character': 'Mr. Potato Head (voice)', 'credit_id': '52fe4284c3a36847f8024f9d', 'gender': 2, 'id': 7167, 'name': 'Don Rickles', 'order': 2, 'profile_path': '/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg'}, {'cast_id': 17, 'character': 'Slinky Dog (voice)', 'credit_id': '52fe4284c3a36847f8024fa1', 'gender': 2, 'id': 12899, 'name': 'Jim Varney', 'order': 3, 'profile_path': '/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg'}, {'cast_id': 18, 'character': 'Rex (voice)', 'credit_id': '52fe4284c3a36847f8024fa5', 'gender': 2, 'id': 12900, 'name': 'Wallace Shawn', 'order': 4, 'profile_path': '/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg'}, {'cast_id': 19, 'character': 'Hamm (voice)', 'credit_id': '52fe4284c3a36847f8024fa9', 'gender': 2, 'id': 7907, 'name': 'John Ratzenberger', 'order': 5, 'profile_path': '/yGechiKWL6TJDfVE2KPSJYqdMsY.jpg'}, {'cast_id': 20, 'character': 'Bo Peep (voice)', 'credit_id': '52fe4284c3a36847f8024fad', 'gender': 1, 'id': 8873, 'name': 'Annie Potts', 'order': 6, 'profile_path': '/eryXT84RL41jHSJcMy4kS3u9y6w.jpg'}, {'cast_id': 26, 'character': 'Andy (voice)', 'credit_id': '52fe4284c3a36847f8024fc1', 'gender': 0, 'id': 1116442, 'name': 'John Morris', 'order': 7, 'profile_path': '/vYGyvK4LzeaUCoNSHtsuqJUY15M.jpg'}, {'cast_id': 22, 'character': 'Sid (voice)', 'credit_id': '52fe4284c3a36847f8024fb1', 'gender': 2, 'id': 12901, 'name': 'Erik von Detten', 'order': 8, 'profile_path': '/twnF1ZaJ1FUNUuo6xLXwcxjayBE.jpg'}, {'cast_id': 23, 'character': 'Mrs. Davis (voice)', 'credit_id': '52fe4284c3a36847f8024fb5', 'gender': 1, 'id': 12133, 'name': 'Laurie Metcalf', 'order': 9, 'profile_path': '/unMMIT60eoBM2sN2nyR7EZ2BvvD.jpg'}, {'cast_id': 24, 'character': 'Sergeant (voice)', 'credit_id': '52fe4284c3a36847f8024fb9', 'gender': 2, 'id': 8655, 'name': 'R. Lee Ermey', 'order': 10, 'profile_path': '/r8GBqFBjypLUP9VVqDqfZ7wYbSs.jpg'}, {'cast_id': 25, 'character': 'Hannah (voice)', 'credit_id': '52fe4284c3a36847f8024fbd', 'gender': 1, 'id': 12903, 'name': 'Sarah Freeman', 'order': 11, 'profile_path': None}, {'cast_id': 27, 'character': 'TV Announcer (voice)', 'credit_id': '52fe4284c3a36847f8024fc5', 'gender': 2, 'id': 37221, 'name': 'Penn Jillette', 'order': 12, 'profile_path': '/zmAaXUdx12NRsssgHbk1T31j2x9.jpg'}]
crew:  <class 'str'>

In [5]:
#Creamos función que convierte los datos de string a:  diccionario o lista de diccionario
import ast 
def convert_to_dicc(string_a_dicc):
    if type(string_a_dicc)== str:
        return ast.literal_eval(string_a_dicc)
    else:
        return  np.nan

#Aplicamos la función a las columnas 
data_movies_credits['genres']= data_movies_credits['genres'].apply(convert_to_dicc) #lista de diccionario
data_movies_credits['belongs_to_collection']=data_movies_credits['belongs_to_collection'].apply(convert_to_dicc) #diccionario
data_movies_credits['production_companies']=data_movies_credits['production_companies'].apply(convert_to_dicc) #lista de diccionario
data_movies_credits['production_countries']=data_movies_credits['production_countries'].apply(convert_to_dicc) #lista de diccionario
data_movies_credits['spoken_languages']=data_movies_credits['spoken_languages'].apply(convert_to_dicc) #lista de diccionario
data_movies_credits['cast']=data_movies_credits['cast'].apply(convert_to_dicc) #lista de diccionario
data_movies_credits['crew']=data_movies_credits['crew'].apply(convert_to_dicc) #lista de diccionario

In [10]:
data_movies_credits

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,...,spoken_languages,status,tagline,title,vote_average,vote_count,return,release_year,cast,crew
0,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000.0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,7.7,5415.0,12.451801,1995,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,NaN,65000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,en,When siblings Judy and Peter discover an encha...,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0,4.043035,1995,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0.0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,en,A family wedding reignites the ancient feud be...,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0,0.000000,1995,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,NaN,16000000.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0,5.090760,1995,"[{'cast_id': 1, 'character': 'Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,"{'id': 96871, 'name': 'Father of the Bride Col...",0.0,"[{'id': 35, 'name': 'Comedy'}]",11862,en,Just when George Banks has recovered from his ...,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0,0.000000,1995,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45446,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",30840,en,"Yet another version of the classic epic, with ...",5.683753,"[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1991-05-13,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Robin Hood,5.7,26.0,0.000000,1991,"[{'cast_id': 1, 'character': 'Sir Robert Hode'...","[{'credit_id': '52fe44439251416c9100a899', 'de..."
45447,NaN,0.0,"[{'id': 18, 'name': 'Drama'}]",111109,tl,An artist struggles to finish his work while a...,0.178241,"[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,...,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,9.0,3.0,0.000000,2011,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de..."
45448,NaN,0.0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",67758,en,"When one of her hits goes wrong, a professiona...",0.903007,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,3.8,6.0,0.000000,2003,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de..."
45449,NaN,0.0,[],227506,en,"In a small town live two brothers, one a minis...",0.003503,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,...,[],Released,NaN,Satan Triumphant,0.0,0.0,0.000000,1917,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de..."
45450,NaN,0.0,[],461257,en,50 years after decriminalisation of homosexual...,0.163015,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,0.0,0.0,0.000000,2017,[],"[{'credit_id': '593e676c92514105b702e68e', 'de..."

In [6]:
#Creamos función que regresa en forma de LISTAS los campos keys de nombre
#Funciona para las columnas: genre, companies, countries, languages, cast
def convertir_a_lista(string_a_dicc):
    if type(string_a_dicc)== list:
        lista_vacia=[]
        for i in string_a_dicc:
            lista_vacia.append(i['name'])
        return lista_vacia
    else:
        return  np.nan
    

#Creamos función que regresa en forma de STRING  los campos keys= director
#Funciona para las columna: crew
def convertir_a_director(string_a_dicc):
    if type(string_a_dicc)== list:
        for i in string_a_dicc:
            if i['job']=='Director': 
                return i['name']
    else:
        return  np.nan
    #Creamos función que regresa en forma de LISTA los campos keys= director
#Funciona para las columna: crew
def convertir_a_director_lista(string_a_dicc):
    if type(string_a_dicc)== list:
        lista_director=[]
        for i in string_a_dicc:
            if i['job']=='Director': 
                lista_director.append(i['name'])
                return lista_director
    else:
        return  np.nan


#Creamos función que regresa listas con el nombre de la coleccion
#Funciona para las columna: belongs_to_collection
def lista_collection(string_a_dicc):
    if type(string_a_dicc)== dict:
        return string_a_dicc['name']
    else:
        return  np.nan
    
    
#Aplicamos la función para cada columna 
data_movies_credits['genres']= data_movies_credits['genres'].apply(convertir_a_lista)
data_movies_credits['production_companies']=data_movies_credits['production_companies'].apply(convertir_a_lista)
data_movies_credits['production_countries']=data_movies_credits['production_countries'].apply(convertir_a_lista)
data_movies_credits['spoken_languages']=data_movies_credits['spoken_languages'].apply(convertir_a_lista)
data_movies_credits['cast']=data_movies_credits['cast'].apply(convertir_a_lista)
data_movies_credits['crew']=data_movies_credits['crew'].apply(convertir_a_director_lista)
data_movies_credits['belongs_to_collection']=data_movies_credits['belongs_to_collection'].apply(lista_collection)

In [7]:
#Se eliminan las peliculas cuyo estatus es diferente a Released
data_movies_credits=data_movies_credits[data_movies_credits['status']=='Released']

El dataset "data_movies_credits" contiene las columnas desanidadas en listas con todas las columnas.

In [8]:
type(data_movies_credits['production_countries'][0])

list

In [9]:
data_movies_credits

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,...,spoken_languages,status,tagline,title,vote_average,vote_count,return,release_year,cast,crew
0,Toy Story Collection,30000000.0,"[Animation, Comedy, Family]",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,[Pixar Animation Studios],[United States of America],1995-10-30,...,[English],Released,NaN,Toy Story,7.7,5415.0,12.451801,1995,"[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...",[John Lasseter]
1,NaN,65000000.0,"[Adventure, Fantasy, Family]",8844,en,When siblings Judy and Peter discover an encha...,17.015539,"[TriStar Pictures, Teitler Film, Interscope Co...",[United States of America],1995-12-15,...,"[English, Français]",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0,4.043035,1995,"[Robin Williams, Jonathan Hyde, Kirsten Dunst,...",[Joe Johnston]
2,Grumpy Old Men Collection,0.0,"[Romance, Comedy]",15602,en,A family wedding reignites the ancient feud be...,11.7129,"[Warner Bros., Lancaster Gate]",[United States of America],1995-12-22,...,[English],Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0,0.000000,1995,"[Walter Matthau, Jack Lemmon, Ann-Margret, Sop...",[Howard Deutch]
3,NaN,16000000.0,"[Comedy, Drama, Romance]",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,[Twentieth Century Fox Film Corporation],[United States of America],1995-12-22,...,[English],Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0,5.090760,1995,"[Whitney Houston, Angela Bassett, Loretta Devi...",[Forest Whitaker]
4,Father of the Bride Collection,0.0,[Comedy],11862,en,Just when George Banks has recovered from his ...,8.387519,"[Sandollar Productions, Touchstone Pictures]",[United States of America],1995-02-10,...,[English],Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0,0.000000,1995,"[Steve Martin, Diane Keaton, Martin Short, Kim...",[Charles Shyer]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45446,NaN,0.0,"[Drama, Action, Romance]",30840,en,"Yet another version of the classic epic, with ...",5.683753,"[Westdeutscher Rundfunk (WDR), Working Title F...","[Canada, Germany, United Kingdom, United State...",1991-05-13,...,[English],Released,NaN,Robin Hood,5.7,26.0,0.000000,1991,"[Patrick Bergin, Uma Thurman, David Morrissey,...",[John Irvin]
45447,NaN,0.0,[Drama],111109,tl,An artist struggles to finish his work while a...,0.178241,[Sine Olivia],[Philippines],2011-11-17,...,[],Released,NaN,Century of Birthing,9.0,3.0,0.000000,2011,"[Angel Aquino, Perry Dizon, Hazel Orencio, Joe...",[Lav Diaz]
45448,NaN,0.0,"[Action, Drama, Thriller]",67758,en,"When one of her hits goes wrong, a professiona...",0.903007,[American World Pictures],[United States of America],2003-08-01,...,[English],Released,A deadly game of wits.,Betrayal,3.8,6.0,0.000000,2003,"[Erika Eleniak, Adam Baldwin, Julie du Page, J...",[Mark L. Lester]
45449,NaN,0.0,[],227506,en,"In a small town live two brothers, one a minis...",0.003503,[Yermoliev],[Russia],1917-10-21,...,[],Released,NaN,Satan Triumphant,0.0,0.0,0.000000,1917,"[Iwan Mosschuchin, Nathalie Lissenko, Pavel Pa...",[Yakov Protazanov]
45450,NaN,0.0,[],461257,en,50 years after decriminalisation of homosexual...,0.163015,[],[United Kingdom],2017-06-09,...,[English],Released,NaN,Queerama,0.0,0.0,0.000000,2017,[],[Daisy Asquith]

Exportamos el archivo en formato csv para poder hacer las consultas en API

In [33]:
data_movies_credits.to_csv('data_movies_credits_datos_filtrados',index=False)

A partir de aqui se crea otro dataframe llamado "data_modelo" para Machine Learning.

In [10]:
#Selección de columnas y cambio de nombre a dichas columnas 
data_modelo=data_movies_credits[['id','title','original_language','overview','genres','cast','crew']]
data_modelo.columns = ['id_pelicula', 'titulo','idioma_original', 'sinopsis', 'genero', 'actores', 'director']

In [11]:
data_modelo

,id_pelicula,titulo,idioma_original,sinopsis,genero,actores,director
0,862,Toy Story,en,"Led by Woody, Andy's toys live happily in his ...","[Animation, Comedy, Family]","[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...",[John Lasseter]
1,8844,Jumanji,en,When siblings Judy and Peter discover an encha...,"[Adventure, Fantasy, Family]","[Robin Williams, Jonathan Hyde, Kirsten Dunst,...",[Joe Johnston]
2,15602,Grumpier Old Men,en,A family wedding reignites the ancient feud be...,"[Romance, Comedy]","[Walter Matthau, Jack Lemmon, Ann-Margret, Sop...",[Howard Deutch]
3,31357,Waiting to Exhale,en,"Cheated on, mistreated and stepped on, the wom...","[Comedy, Drama, Romance]","[Whitney Houston, Angela Bassett, Loretta Devi...",[Forest Whitaker]
4,11862,Father of the Bride Part II,en,Just when George Banks has recovered from his ...,[Comedy],"[Steve Martin, Diane Keaton, Martin Short, Kim...",[Charles Shyer]
...,...,...,...,...,...,...,...
45446,30840,Robin Hood,en,"Yet another version of the classic epic, with ...","[Drama, Action, Romance]","[Patrick Bergin, Uma Thurman, David Morrissey,...",[John Irvin]
45447,111109,Century of Birthing,tl,An artist struggles to finish his work while a...,[Drama],"[Angel Aquino, Perry Dizon, Hazel Orencio, Joe...",[Lav Diaz]
45448,67758,Betrayal,en,"When one of her hits goes wrong, a professiona...","[Action, Drama, Thriller]","[Erika Eleniak, Adam Baldwin, Julie du Page, J...",[Mark L. Lester]
45449,227506,Satan Triumphant,en,"In a small town live two brothers, one a minis...",[],"[Iwan Mosschuchin, Nathalie Lissenko, Pavel Pa...",[Yakov Protazanov]
45450,461257,Queerama,en,50 years after decriminalisation of homosexual...,[],[],[Daisy Asquith]

In [12]:
#La columna sinopsis la convertimos en lista
def quitar_espacios_sinopsis(texto):
    if type(texto) == str:
        #print('Es texto')
        return texto.split()
    else:
        return np.nan 
    
#Aplicamos la función
data_modelo['sinopsis']= data_modelo['sinopsis'].apply(quitar_espacios_sinopsis)

C:\Users\Jocelyn\AppData\Local\Temp\ipykernel_5468\3509295762.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_modelo['sinopsis']= data_modelo['sinopsis'].apply(quitar_espacios_sinopsis)

In [13]:
data_modelo.head(2)

,id_pelicula,titulo,idioma_original,sinopsis,genero,actores,director
0,862,Toy Story,en,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...",[John Lasseter]
1,8844,Jumanji,en,"[When, siblings, Judy, and, Peter, discover, a...","[Adventure, Fantasy, Family]","[Robin Williams, Jonathan Hyde, Kirsten Dunst,...",[Joe Johnston]

In [14]:
#Creamos una copia del modelo 
data_modelo_copia=data_modelo

In [15]:
#Quitamos espacios de las columnas GENERO, ACTORES y Director

#Funciona para la columna GENERO y ACTORES, quita espacios de las i cuando es tipo [(i),(i),(i),(i)]
data_modelo_copia['genero']=data_modelo_copia['genero'].apply(lambda x:[i.replace(" ","") for i in x])
data_modelo_copia['actores']=data_modelo_copia['actores'].apply(lambda x:[i.replace(" ","") for i in x])

#Funciona para la columna DIRECTOR
#Funciona si es tipo lista
def quitar_espacios_director(texto):
    if type(texto) == list:
        lista_vacia=[]
        for i in texto: 
            lista_vacia.append(i.replace(" ",""))
        return lista_vacia
    else:
        return np.nan 

#Se aplica la función a la columna DIRECTOR 
data_modelo_copia['director']= data_modelo_copia['director'].apply(quitar_espacios_director)

C:\Users\Jocelyn\AppData\Local\Temp\ipykernel_5468\4220922176.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_modelo_copia['genero']=data_modelo_copia['genero'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\Jocelyn\AppData\Local\Temp\ipykernel_5468\4220922176.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_modelo_copia['actores']=data_modelo_copia['actores'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\Jocelyn\AppData\Local\Temp\ipykernel_5468\4220922176.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_modelo_copia['director']= data_modelo_copia['director'].apply(quitar_espacios_director)

In [16]:
data_modelo_copia

,id_pelicula,titulo,idioma_original,sinopsis,genero,actores,director
0,862,Toy Story,en,"[Led, by, Woody,, Andy's, toys, live, happily,...","[Animation, Comedy, Family]","[TomHanks, TimAllen, DonRickles, JimVarney, Wa...",[JohnLasseter]
1,8844,Jumanji,en,"[When, siblings, Judy, and, Peter, discover, a...","[Adventure, Fantasy, Family]","[RobinWilliams, JonathanHyde, KirstenDunst, Br...",[JoeJohnston]
2,15602,Grumpier Old Men,en,"[A, family, wedding, reignites, the, ancient, ...","[Romance, Comedy]","[WalterMatthau, JackLemmon, Ann-Margret, Sophi...",[HowardDeutch]
3,31357,Waiting to Exhale,en,"[Cheated, on,, mistreated, and, stepped, on,, ...","[Comedy, Drama, Romance]","[WhitneyHouston, AngelaBassett, LorettaDevine,...",[ForestWhitaker]
4,11862,Father of the Bride Part II,en,"[Just, when, George, Banks, has, recovered, fr...",[Comedy],"[SteveMartin, DianeKeaton, MartinShort, Kimber...",[CharlesShyer]
...,...,...,...,...,...,...,...
45446,30840,Robin Hood,en,"[Yet, another, version, of, the, classic, epic...","[Drama, Action, Romance]","[PatrickBergin, UmaThurman, DavidMorrissey, Jü...",[JohnIrvin]
45447,111109,Century of Birthing,tl,"[An, artist, struggles, to, finish, his, work,...",[Drama],"[AngelAquino, PerryDizon, HazelOrencio, JoelTo...",[LavDiaz]
45448,67758,Betrayal,en,"[When, one, of, her, hits, goes, wrong,, a, pr...","[Action, Drama, Thriller]","[ErikaEleniak, AdamBaldwin, JulieduPage, James...",[MarkL.Lester]
45449,227506,Satan Triumphant,en,"[In, a, small, town, live, two, brothers,, one...",[],"[IwanMosschuchin, NathalieLissenko, PavelPavlo...",[YakovProtazanov]
45450,461257,Queerama,en,"[50, years, after, decriminalisation, of, homo...",[],[],[DaisyAsquith]

In [25]:
#ESTE NO SIRVIÓ PORQUE ME MARCABA TAGS= NAN

#Se crea la columna tags con toda la información de las demás columnas, 
#Esto sólo se puede hacer si todas las columnas que estamos sumando son de tipo lista


#data_modelo_copia['tags']=data_modelo_copia['sinopsis']+data_modelo_copia['actores']+ data_modelo_copia['genero']+data_modelo_copia['director']

C:\Users\Jocelyn\AppData\Local\Temp\ipykernel_15656\2183197097.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_modelo_copia['tags']=data_modelo_copia['sinopsis']+data_modelo_copia['actores']+ data_modelo_copia['genero']+data_modelo_copia['director']

In [17]:
#Se crea la columna tags con toda la información de las demás columnas
data_modelo_copia['tags'] = (
    data_modelo_copia['titulo'].fillna('') + ' ' +
    data_modelo_copia['idioma_original'].fillna('') + ' ' +
    data_modelo_copia['sinopsis'].apply(lambda x: ' '.join(x) if isinstance(x, list) else '').replace(np.nan, '') + ' ' +
    data_modelo_copia['genero'].apply(lambda x: ' '.join(x) if isinstance(x, list) else '').replace(np.nan, '') + ' ' +
    data_modelo_copia['actores'].apply(lambda x: ' '.join(x) if isinstance(x, list) else '').replace(np.nan, '') + ' ' +
    data_modelo_copia['director'].apply(lambda x: ' '.join(x) if isinstance(x, list) else '').replace(np.nan, '')
)

#Quito las mayúsculas de la columna tags
data_modelo_copia['tags'] = data_modelo_copia['tags'].str.lower()

C:\Users\Jocelyn\AppData\Local\Temp\ipykernel_5468\921407896.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_modelo_copia['tags'] = (
C:\Users\Jocelyn\AppData\Local\Temp\ipykernel_5468\921407896.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_modelo_copia['tags'] = data_modelo_copia['tags'].str.lower()

In [18]:
#Ahora que se ha creado la columna tags, 
# Se re seleccionan las columnas para simplificar el dataframe 
data_tags=data_modelo_copia[['id_pelicula', 'titulo','tags']]
data_tags

,id_pelicula,titulo,tags
0,862,Toy Story,"toy story en led by woody, andy's toys live ha..."
1,8844,Jumanji,jumanji en when siblings judy and peter discov...
2,15602,Grumpier Old Men,grumpier old men en a family wedding reignites...
3,31357,Waiting to Exhale,"waiting to exhale en cheated on, mistreated an..."
4,11862,Father of the Bride Part II,father of the bride part ii en just when georg...
...,...,...,...
45446,30840,Robin Hood,robin hood en yet another version of the class...
45447,111109,Century of Birthing,century of birthing tl an artist struggles to ...
45448,67758,Betrayal,"betrayal en when one of her hits goes wrong, a..."
45449,227506,Satan Triumphant,satan triumphant en in a small town live two b...
45450,461257,Queerama,queerama en 50 years after decriminalisation o...

In [57]:
data_tags['tags'][0]

"toy story en led by woody, andy's toys live happily in his room until andy's birthday brings buzz lightyear onto the scene. afraid of losing his place in andy's heart, woody plots against buzz. but when circumstances separate buzz and woody from their owner, the duo eventually learns to put aside their differences. animation comedy family tomhanks timallen donrickles jimvarney wallaceshawn johnratzenberger anniepotts johnmorris erikvondetten lauriemetcalf r.leeermey sarahfreeman pennjillette johnlasseter"

Hay muchas palabras que tienen la misma raíz:
De esto: ['loved', 'loving', 'love']
Necesitamos que sea así: ['love','love','love']

In [141]:
# ps.stem('loving')

'love'

In [19]:
import nltk 
from nltk.stem.porter import PorterStemmer

#Creamos el objeto 
ps=PorterStemmer()

def stem(texto):
    y=[]
    #Aquí se itera a través de las palabras en el texto, 
    # usando el método split() que divide el texto en palabras separadas 
    # por espacios en blanco. En cada iteración, una palabra se 
    # almacena temporalmente en la variable i.
    for i in texto.split():
        #La función stem() se aplica a cada palabra i,
        y.append(ps.stem(i))
    return " ".join(y)

In [59]:
#La función se aplica para el primer valor para saber que funciona 
stem(data_tags['tags'][0])

"toy stori en led by woody, andy' toy live happili in hi room until andy' birthday bring buzz lightyear onto the scene. afraid of lose hi place in andy' heart, woodi plot against buzz. but when circumst separ buzz and woodi from their owner, the duo eventu learn to put asid their differences. anim comedi famili tomhank timallen donrickl jimvarney wallaceshawn johnratzenberg anniepott johnmorri erikvondetten lauriemetcalf r.leeermey sarahfreeman pennjillett johnlasset"

In [20]:
data_tags['tags']=data_tags['tags'].apply(stem)

C:\Users\Jocelyn\AppData\Local\Temp\ipykernel_5468\3727730754.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_tags['tags']=data_tags['tags'].apply(stem)

In [21]:
data_tags.head(3)

,id_pelicula,titulo,tags
0,862,Toy Story,"toy stori en led by woody, andy' toy live happ..."
1,8844,Jumanji,jumanji en when sibl judi and peter discov an ...
2,15602,Grumpier Old Men,grumpier old men en a famili wed reignit the a...

In [38]:
data_tags.reset_index(drop=True, inplace=True)

In [39]:
data_tags

,id_pelicula,titulo,tags
0,862,Toy Story,"toy stori en led by woody, andy' toy live happ..."
1,8844,Jumanji,jumanji en when sibl judi and peter discov an ...
2,15602,Grumpier Old Men,grumpier old men en a famili wed reignit the a...
3,31357,Waiting to Exhale,"wait to exhal en cheat on, mistreat and step o..."
4,11862,Father of the Bride Part II,father of the bride part ii en just when georg...
...,...,...,...
44931,30840,Robin Hood,robin hood en yet anoth version of the classic...
44932,111109,Century of Birthing,centuri of birth tl an artist struggl to finis...
44933,67758,Betrayal,"betray en when one of her hit goe wrong, a pro..."
44934,227506,Satan Triumphant,satan triumphant en in a small town live two b...
44935,461257,Queerama,queerama en 50 year after decriminalis of homo...

SK LEARN

In [40]:
#CountVectorizer es una herramienta de procesamiento de lenguaje natural (NLP) que se utiliza para 
#convertir una colección de documentos de texto en una matriz de recuento de palabras o tokens.
from sklearn.feature_extraction.text import CountVectorizer
#En este caso, se seleccionan las 2500 palabras más frecuentes 
#Este parámetro especifica que las palabras de parada (stop words) en inglés deben ser excluidas del análisis. 
#Las palabras de parada son palabras comunes que a menudo no aportan un significado relevante en el análisis de texto
#(por ejemplo: "el", "es", "y", "un", etc.). Al especificar 'english', CountVectorizer utilizará una lista
#predeterminada de palabras de parada en inglés.
cv = CountVectorizer(max_features=2500,stop_words='english')

In [41]:
#Se aplica el CountVectorizer a la columna tags
#Es decir, se crearon vectores para cada película 
vectors= cv.fit_transform(data_tags['tags']).toarray()

In [42]:
#Número de películas que tenemos en nuestro dataframe: 29681
#LAs 5000 palabras que especificamos 
print('El arreglo de vectores tiene una dimen de ',vectors.shape ) #salida --> (44936, 2500)

#Este sería la matriz para la primer película
print(vectors[0])

## Te devuelve el array con los nombres de las películas
cv.get_feature_names_out()

El arreglo de vectores tiene una dimen de  (44936, 2500)
[0 0 0 ... 0 0 0]

array(['000', '10', '100', ..., 'zh', 'zombi', 'zone'], dtype=object)

In [24]:
from sklearn.metrics.pairwise import cosine_similarity
#Se crea la matriz de similarididad, es decir, ya que hemos creado un vector por cada película
#Se mide la distancia entre ellos para deducir la similitud. Entre más distancia menos similitud
#distancia = 1/similitud   (inversamente proporcional )
#Para 1 vector (1 película) se calculan 44936  ángulos, es decir una matriz de  (44936X44936)
similarity = cosine_similarity(vectors)

In [43]:
def recomendacion(pelicula):
    #Busca el índice de la película que queremos
    movie_index= data_tags[data_tags['titulo']==pelicula].index[0]
    distancia =similarity[movie_index]
    # list(enumerate(similarity[0]))
    #Enumera cada elemento del array similarity[0] y lo guarda en 
    # forma de lista de tuplas es decir:
    # [(0, 1),(1, 0.11572751247156893),(2, 0.08559209850218259),,...]

    #Con enumerate lo Ordenamos de mayor a menor , 
    # key es para una condición al ordenar, en este caso
    #de la lista de tuplas la vas a ordenar tomando el valor x[1] (x,[0],x[1])
    #y me vas a mostrar los 5 primeros valores 
    #Así ya optenemos el índice de las películas que tienen más similitud
    top_5= sorted(list(enumerate(distancia)),reverse=True,key=lambda x:x[1])[1:6]
    recomendaciones=[]
    for j in top_5:
        recomendaciones.append(data_tags.iloc[j[0]].titulo)
    return recomendaciones

In [51]:
#probamos que la función funcione correctamente
recomendacion('Father of the Bride Part II')

['Father of the Bride',
 'About Schmidt',
 'Babbitt',
 'Wild Mouse',
 'All Night Long']

Aplicamos la función de recomendación para cada una de las películas que tenemos y creamos un nuevo dataframe para poder usarlo en el deploy y facilitarlo

In [47]:
# Aplicar la función a la columna "pelicula_column"
data_tags['recomendaciones'] = data_tags['titulo'].apply(recomendacion)

C:\Users\Jocelyn\AppData\Local\Temp\ipykernel_5468\3935680267.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_tags['recomendaciones'] = data_tags['titulo'].apply(recomendacion)

In [48]:
data_tags

,id_pelicula,titulo,tags,recomendaciones
0,862,Toy Story,"toy stori en led by woody, andy' toy live happ...","[Toy Story 2, Partysaurus Rex, Walk Like a Man..."
1,8844,Jumanji,jumanji en when sibl judi and peter discov an ...,"[Table No. 21, Liar Game: Reborn, The Games Ma..."
2,15602,Grumpier Old Men,grumpier old men en a famili wed reignit the a...,"[Grumpy Old Men, Go Fish, Gone Fishin', Heartb..."
3,31357,Waiting to Exhale,"wait to exhal en cheat on, mistreat and step o...","[Waiting for Godot, The Cyclone, Ciudad Deliri..."
4,11862,Father of the Bride Part II,father of the bride part ii en just when georg...,"[Father of the Bride, About Schmidt, Babbitt, ..."
...,...,...,...,...
44931,30840,Robin Hood,robin hood en yet anoth version of the classic...,"[Robin Hood: Men in Tights, The Story of Robin..."
44932,111109,Century of Birthing,centuri of birth tl an artist struggl to finis...,"[Killer of Sheep, Me and Charly, Caravaggio, F..."
44933,67758,Betrayal,"betray en when one of her hit goe wrong, a pro...","[Written on the Wind, Darling Companion, Clash..."
44934,227506,Satan Triumphant,satan triumphant en in a small town live two b...,"[Nayak: The Real Hero, Your Vice is a Locked R..."
44935,461257,Queerama,queerama en 50 year after decriminalis of homo...,"[Re-Kill, The Men Next Door, The Adonis Factor..."

In [49]:
data_recomendaciones_final= data_tags[['titulo','recomendaciones']]

In [50]:
data_recomendaciones_final.to_csv('data_recomendaciones_final',index=False)